# -*- coding: utf-8 -*-
# Copyright (c) 2025, BrainWise and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class OfflineOperationSync(Document):
    """
    Tracks offline write-operation synchronization to prevent duplicate submissions.

    Generic counterpart of Offline Invoice Sync: each record maps an op_id
    (generated client-side) to the document created on the server for a given
    operation type (open_shift, close_shift, attendance, daily_payment, customer, ...).
    """

    def before_insert(self):
        """Set synced_at timestamp before insert."""
        if not self.synced_at:
            self.synced_at = frappe.utils.now_datetime()

    @staticmethod
    def create_sync_record(op_id, op_type=None, ref_doctype=None, ref_name=None, status="Synced"):
        """
        Create (or update) a sync record for an offline operation.

        Args:
            op_id: The unique operation ID generated by the client
            op_type: Operation type string (e.g. "attendance", "daily_payment")
            ref_doctype: The DocType created on the server
            ref_name: The document name created on the server
            status: "Pending", "Synced", or "Failed"

        Returns:
            The created/updated OfflineOperationSync document, or None if no op_id.
        """
        if not op_id:
            return None

        existing = frappe.db.get_value(
            "Offline Operation Sync",
            {"op_id": op_id},
            ["name", "status"],
            as_dict=True,
        )

        if existing:
            # Promote a previously Pending record to Synced once the doc exists
            if existing.status == "Pending" and status == "Synced" and ref_name:
                sync_doc = frappe.get_doc("Offline Operation Sync", existing.name)
                sync_doc.op_type = op_type or sync_doc.op_type
                sync_doc.ref_doctype = ref_doctype or sync_doc.ref_doctype
                sync_doc.ref_name = ref_name
                sync_doc.status = "Synced"
                sync_doc.synced_at = frappe.utils.now_datetime()
                sync_doc.flags.ignore_permissions = True
                sync_doc.save()
            return frappe.get_doc("Offline Operation Sync", existing.name)

        doc = frappe.get_doc({
            "doctype": "Offline Operation Sync",
            "op_id": op_id,
            "op_type": op_type,
            "ref_doctype": ref_doctype,
            "ref_name": ref_name or "",
            "status": status,
        })
        doc.flags.ignore_permissions = True
        doc.insert()
        return doc

    @staticmethod
    def is_synced(op_id):
        """
        Check whether an op_id has already been processed on the server.

        Returns:
            dict with 'synced' (bool), 'ref_doctype', 'ref_name', and 'status'.
        """
        if not op_id:
            return {"synced": False, "ref_doctype": None, "ref_name": None, "status": None}

        existing = frappe.db.get_value(
            "Offline Operation Sync",
            {"op_id": op_id},
            ["ref_doctype", "ref_name", "status"],
            as_dict=True,
        )

        if existing:
            is_synced = existing.status == "Synced" and bool(existing.ref_name)
            return {
                "synced": is_synced,
                "ref_doctype": existing.ref_doctype if is_synced else None,
                "ref_name": existing.ref_name if is_synced else None,
                "status": existing.status,
            }

        return {"synced": False, "ref_doctype": None, "ref_name": None, "status": None}
